### ISSUE TITLE
077 [C++]

### ISSUE THREAD

**Issue by alphaWizard** [vaibhav29498/HackerrankProjectEuler#16]
#### This issue is about [077] (https://www.hackerrank.com/contests/projecteuler/challenges/euler077).

- [x] Issue Title is in form Problem Number [Language].
- [x] Language is either of C,C++,Python (IMPORTANT)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).
- [x] Assign this issue to me (I want to work on this).
- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by sirjan13** [comment]
Go For It 👍
