### ISSUE TITLE
Problem Number 27 [C]

### ISSUE THREAD

**Issue by prateekiiest** [vaibhav29498/HackerrankProjectEuler#23]
#### This issue is about [Problem No] (link to the Hackerrank Euler Problem).

- [x] Issue Title is in form `Problem Number [Language]`.
- [x] Language is either of C,C++,Python (IMPORTANT)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).

**Comment by sirjan13** [comment]
Is your solution accepted on Hackerrank?

**Comment by sirjan13** [comment]
Plz check the box for AC solution here and also change the issue totle as per specified guidelines

**Comment by prateekiiest** [comment]
Done @sirjan13 
Would you please had "hacktoberfest" for this issue ? 😃

**Comment by sirjan13** [comment]
Sure :)
