### ISSUE TITLE
#63 [C]

### ISSUE THREAD

**Issue by flavian11** [vaibhav29498/HackerrankProjectEuler#27]
#### This issue is about #63 (link to the Hackerrank Euler Problem).

- [X] Issue Title is in form `Problem Number [Language]`.
- [X] Language is either of C,C++,Python (IMPORTANT)
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] A solution is already present on the repo but my solution is better. (Please explain how your solution performs better)
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).
- [X] Assign this issue to me (I want to work on this).
- [X] I ensure that I am not already assigned to 2 or more issues.
- [X] I will send my PR only after I'm assigned to this issue by any maintainer.
- [X] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by vaibhav29498** [comment]
Assigned. Please ensure that you have got an AC on Hackerrank for this problem before submitting the solution.
