### ISSUE TITLE
096[C]

### ISSUE THREAD

**Issue by ReimuA** [vaibhav29498/HackerrankProjectEuler#28]
#### This issue is about [Problem 96] (https://www.hackerrank.com/contests/projecteuler/challenges/euler096).

- [x] Issue Title is in form `Problem Number [Language]`.
- [x] Language is either of C,C++,Python (IMPORTANT)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] Assign this issue to me (I want to work on this).
- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by vaibhav29498** [comment]
Assigned
