### ISSUE TITLE
015 [C++]

### ISSUE THREAD

**Issue by Sanskar-Jain** [vaibhav29498/HackerrankProjectEuler#8]
#### This issue is about [Problem No] (link to the Hackerrank Euler Problem).

- [x] Issue Title is in form `Problem Number [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] I got AC for this problem on Hackerrank.
- [x] I have checked that my solution is passing on Problem (in case you make some changes).
- [x] Assign this issue to me (I want to work on this).
- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Comment by sirjan13** [comment]
Assigned

**Comment by vaibhav29498** [comment]
Unassigned.
